/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bci_SerialPort_Native */

#ifndef _Included_bci_SerialPort_Native
#define _Included_bci_SerialPort_Native
#ifdef __cplusplus
extern "C" {
#endif
   /*
   * Class:     bci_SerialPort_Native
   * Method:    getAllPorts
   * Signature: ()[Ljava/lang/String;
   */
   JNIEXPORT jobjectArray JNICALL Java_bci_SerialPort_00024Native_getAllPorts(JNIEnv *, jclass);

   /*
   * Class:     bci_SerialPort_Native
   * Method:    initialize
   * Signature: (Ljava/lang/String;)J
   */
   JNIEXPORT jlong JNICALL Java_bci_SerialPort_00024Native_initialize(JNIEnv *, jclass, jstring);

   /*
   * Class:     bci_SerialPort_Native
   * Method:    setBaudRate
   * Signature: (JI)V
   */
   JNIEXPORT void JNICALL Java_bci_SerialPort_00024Native_setBaudRate(JNIEnv *, jclass, jlong, jint);

   /*
   * Class:     bci_SerialPort_Native
   * Method:    read
   * Signature: (J)Ljava/lang/String;
   */
   JNIEXPORT jstring JNICALL Java_bci_SerialPort_00024Native_read(JNIEnv *, jclass, jlong);

   /*
   * Class:     bci_SerialPort_Native
   * Method:    write
   * Signature: (JLjava/lang/String;)V
   */
   JNIEXPORT void JNICALL Java_bci_SerialPort_00024Native_write(JNIEnv *, jclass, jlong, jstring);

   /*
   * Class:     bci_SerialPort_Native
   * Method:    finalize
   * Signature: (J)V
   */
   JNIEXPORT void JNICALL Java_bci_SerialPort_00024Native_finalize(JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
